#ifndef RAW_PHYSICS_EXAMPLES_EXAMPLES_H
#define RAW_PHYSICS_EXAMPLES_EXAMPLES_H

typedef enum {
	NONE_EXAMPLE_SCENE,
	DEBUG_EXAMPLE_SCENE,
	SINGLE_CUBE_EXAMPLE_SCENE
} Example_Scene;

#define EXAMPLE_SCENE_INITIAL SINGLE_CUBE_EXAMPLE_SCENE

#endif